import React, { useState, useEffect } from 'react';
import { Search, Loader2, BrainCircuit, Globe, FileText, Activity, ShieldCheck, ChevronRight } from 'lucide-react';
import { apiService } from '../services/apiService';

interface NativeWebSearchProps {
  query: string;
  lang: 'zh' | 'en';
}

export const NativeWebSearch: React.FC<NativeWebSearchProps> = ({ query, lang }) => {
  const [loading, setLoading] = useState(true);
  const [step, setStep] = useState(0);
  const [result, setResult] = useState<any>(null);

  const t = {
    zh: {
      steps: ['连接智能检索引擎...', '正在全网检索相关医疗资讯...', '聚合提取关键信息...', '生成辅助决策报告...'],
      aiTitle: 'MediMate 智能聚合搜索',
      synthesis: 'AI 综合摘要',
      synthesisText: `针对您的查询 "${query}"：目前全网资讯显示，该类需求在近期有多项医疗指引更新。建议您可以优先选择公立三甲医院的相关专科门诊，或者通过我们的专业陪诊师代为您跑腿咨询，为您节省精力。`,
      keyInfo: '关键提取信息',
      sources: '全网来源参考',
      disclaimer: '本报告由 AI 自动聚合全网公开信息生成，仅供参考，不能替代专业医疗建议。',
      source1: '国家卫健委最新就医指南',
      source2: '某三甲总医院官网资讯',
      source3: '患者就医体验论坛交流',
      actionBtn: '匹配对口陪诊师'
    },
    en: {
      steps: ['Connecting to reasoning engine...', 'Searching medical information across the web...', 'Extracting key insights...', 'Generating decision report...'],
      aiTitle: 'MediMate Intelligent Web Search',
      synthesis: 'AI Synthesis',
      synthesisText: `Regarding your query "${query}": Recent web resources indicate updates in medical guidelines related to this. We recommend prioritizing top-tier public hospitals for this specialty, or utilizing our expert escorts to run errands and consult on your behalf to save time.`,
      keyInfo: 'Key Insights extracted',
      sources: 'Web References',
      disclaimer: 'This report is generated by AI aggregating public web info. For reference only, not medical advice.',
      source1: 'National Health Commission Guidelines',
      source2: 'Top-tier Hospital Official News',
      source3: 'Patient Experience Forum',
      actionBtn: 'Match with specialized Escort'
    }
  }[lang];

  useEffect(() => {
    let currentStep = 0;
    let isDataReady = false;
    let fetchedData: any = null;

    const interval = setInterval(() => {
      currentStep++;
      if (currentStep < 4) {
        setStep(currentStep);
      } else {
        if (isDataReady) {
          setResult(fetchedData);
          setLoading(false);
          clearInterval(interval);
        }
        // If data isn't ready by step 4, it stays on the last step "Generating..." until the fetch completes
      }
    }, 800);

    // Call API while animation runs
    apiService.getWebSearchSynthesis(query, lang).then((res) => {
      isDataReady = true;
      fetchedData = res;
      // If the animation is already stuck waiting on step 4
      if (currentStep >= 4) {
        setResult(res);
        setLoading(false);
        clearInterval(interval);
      }
    }).catch((err) => {
      isDataReady = true;
      fetchedData = {
        synthesisText: 'Failed to access AI engine.',
        keyInfo: [{ title: 'Status', val: 'Error' }],
        sources: ['Error fallback']
      };
      if (currentStep >= 4) {
        setResult(fetchedData);
        setLoading(false);
        clearInterval(interval);
      }
    });

    return () => clearInterval(interval);
  }, [query, lang]);

  if (loading) {
    return (
      <div className="w-full h-[500px] bg-slate-50 dark:bg-slate-800 rounded-3xl flex flex-col items-center justify-center p-8 mt-4 border border-slate-100 dark:border-slate-700">
        <div className="relative mb-8">
          <div className="absolute inset-0 bg-teal-500 blur-xl opacity-30 rounded-full animate-pulse"></div>
          <div className="h-20 w-20 bg-white dark:bg-slate-900 rounded-full shadow-xl flex items-center justify-center relative z-10 border border-teal-100 dark:border-teal-900">
            <BrainCircuit className="h-10 w-10 text-teal-500 animate-pulse" />
          </div>
        </div>
        <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-2">{t.aiTitle}</h3>
        <div className="flex items-center gap-3 text-slate-500 dark:text-slate-400 mt-4">
          <Loader2 className="h-5 w-5 animate-spin text-teal-500" />
          <span className="font-medium animate-pulse">{t.steps[step]}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full bg-transparent mt-4 space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      {/* Search Header Banner */}
      <div className="bg-gradient-to-r from-teal-500 to-emerald-600 rounded-3xl p-6 shadow-lg text-white relative overflow-hidden">
        <div className="absolute right-0 top-0 opacity-10 pointer-events-none transform translate-x-4 -translate-y-4">
          <Globe className="h-40 w-40" />
        </div>
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-3">
            <div className="p-2 bg-white/20 rounded-xl backdrop-blur-sm">
              <Search className="h-5 w-5 text-white" />
            </div>
            <span className="font-semibold text-teal-50 tracking-wide uppercase text-xs">{t.aiTitle}</span>
          </div>
          <h2 className="text-2xl font-black mb-1 leading-tight line-clamp-2">&quot;{query}&quot;</h2>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Main Synthesis Result */}
        <div className="col-span-1 md:col-span-2 bg-white dark:bg-slate-800 rounded-3xl p-6 shadow-sm border border-slate-100 dark:border-slate-700 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none group-hover:scale-110 transition-transform duration-500">
            <BrainCircuit className="h-32 w-32" />
          </div>
          <div className="flex items-center gap-2 mb-4">
            <BrainCircuit className="h-5 w-5 text-teal-500" />
            <h3 className="text-lg font-bold text-slate-900 dark:text-white">{t.synthesis}</h3>
          </div>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-[15px]">
            {result?.synthesisText || t.synthesisText}
          </p>
          
          <div className="mt-6 pt-6 border-t border-slate-100 dark:border-slate-700 flex flex-col sm:flex-row gap-3 items-center justify-between">
             <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-50 dark:bg-slate-900 py-1.5 px-3 rounded-full">
               <ShieldCheck className="h-3.5 w-3.5 text-teal-500" />
               {t.disclaimer}
             </div>
             <button className="bg-slate-900 dark:bg-teal-600 hover:bg-teal-600 font-bold text-white text-sm py-2 px-5 rounded-full transition-colors flex items-center gap-2 whitespace-nowrap">
               {t.actionBtn} <ChevronRight className="h-4 w-4" />
             </button>
          </div>
        </div>

        {/* Extracted Data & Sources */}
        <div className="col-span-1 flex flex-col gap-4">
          <div className="bg-white dark:bg-slate-800 rounded-3xl p-5 shadow-sm border border-slate-100 dark:border-slate-700 flex-1">
            <div className="flex items-center gap-2 mb-4">
              <Activity className="h-5 w-5 text-amber-500" />
              <h3 className="font-bold text-slate-900 dark:text-white">{t.keyInfo}</h3>
            </div>
            <ul className="space-y-3">
              {(result?.keyInfo || [
                { title: '预计等待时间', val: '需要提前1周' },
                { title: '陪诊建议时常', val: '半天(4h)较稳妥' },
                { title: '特殊物资需求', val: '携带既往病历本' }
              ]).map((item: any, i: number) => (
                <li key={i} className="flex justify-between items-center text-sm border-b border-slate-50 dark:border-slate-700 pb-2 last:border-0 last:pb-0">
                  <span className="text-slate-500 dark:text-slate-400">{item.title}</span>
                  <span className="font-semibold text-slate-800 dark:text-slate-200">{item.val}</span>
                </li>
              ))}
            </ul>
          </div>
          
          <div className="bg-white dark:bg-slate-800 rounded-3xl p-5 shadow-sm border border-slate-100 dark:border-slate-700">
            <div className="flex items-center gap-2 mb-3">
              <FileText className="h-5 w-5 text-blue-500" />
              <h3 className="font-bold text-slate-900 dark:text-white text-sm">{t.sources}</h3>
            </div>
            <div className="space-y-2">
              {(result?.sources || [t.source1, t.source2, t.source3]).map((s: string, i: number) => (
                <a href="#" key={i} className="block text-xs font-medium text-slate-600 dark:text-slate-300 hover:text-teal-500 dark:hover:text-teal-400 transition-colors p-2 bg-slate-50 dark:bg-slate-700/50 rounded-lg truncate">
                  {i + 1}. {s}
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
